# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: "bellavista"

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: "bellavista"
    salt: "bellavista"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  bellavistamarket.digital:
    env:
      db_password: "bellavista"
      # Generate your keys here: https://roots.io/salts.html
auth_key: "Ab`hP.YiB;dPU4&qJ(xG=7X4dI(/,D1<OR-[^Yb4/]eU)`TGcI/xul8S2eyj,sCC"
secure_auth_key: "b*dsfs-hW-2Cz4cXk4Ii+rx|LK@;97sY:rUNC.$Dc[c%a%t/d<1l!?N[M_zl+QOL"
logged_in_key: "apjwLq*`0U`j&cn7Je4P]q{RzCfW/r%IQT|pgC+Cx_e4GJ`(jKYgp0st5QFK9*dF"
nonce_key: "BwF4gIjcD)pScxs91_)Sm6&#a4QIF{WY6j^%w3_<oCNx+@#1b&J%DOU<Fp)ymK)`"
auth_salt: "K3g?&rr3t^hz-3p:R7v40y}*K5Eplc7a7MkuVOD/.jf_{C`FbE079@;B8_*rB0g|"
secure_auth_salt: "Gz>+(7Cs#NO?3SIM)NY!`Dj=+6%j4jr:/(T04@.3Q=mAxA3+21%XQd5Z9FwbMBou"
logged_in_salt: "pcE+:/L&?.Wk+XWu/|}5%zEEW@{.Jv5&TiLH%O!RDxvS<+$cW-CksTM=X)GYuHT;"
nonce_salt: "=/<496Bpg6m#Hb$]T(8)@MKl`B{e.2{kz.{inqEpPP-M-Qv!:/|E{}zl+I4#32&#"