# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  bellavistamarket.digital:
    site_hosts:
      - canonical: www.josedu.digital
        redirects:
          - josedu.digital
    local_path: ../staging.bellavistamarket.digital # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:josedu90/staging.bellavistamarket.digital.git # replace with your Git repo URL
    repo_subtree_path: bellavistamarket.digital # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
